[[pages]]
path = "_pages/home_page.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "_pages/batter_page.py"
name = "Batter Hub"
icon = "ğŸ"

[[pages]]
path = "_pages/bowler_page.py"
name = "Bowler Hub"
icon = "ğŸ¯"

[[pages]]
path = "_pages/match_page.py"
name = "Match Hub"
icon = "ğŸŸï¸"

