[[pages]]
path = "home_page.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "batter_page.py"
name = "Batter Hub"
icon = "ğŸ"

[[pages]]
path = "bowler_page.py"
name = "Bowler Hub"
icon = "ğŸ¯"

[[pages]]
path = "match_page.py"
name = "Match Hub"
icon = "ğŸŸï¸"

